/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CMSContent {
  'seo' : CMSSEO,
  'terms' : CMSTerms,
  'tagline' : CMSTagline,
}
export interface CMSSEO { 'seoTitle' : string, 'seoMeta' : string }
export interface CMSTagline {
  'tagline' : string,
  'festivalOffer' : string,
  'popupActive' : boolean,
  'popupText' : string,
}
export interface CMSTerms {
  'refundPolicy' : string,
  'privacyPolicy' : string,
  'shippingPolicy' : string,
  'termsAndConditions' : string,
}
export interface DashboardStats {
  'totalOrders' : bigint,
  'subscriptionRevenue' : bigint,
  'dailyRevenue' : bigint,
  'weeklyRevenue' : bigint,
  'monthlyRevenue' : bigint,
}
export interface DeliverySettings {
  'minOrderValue' : bigint,
  'allowedPincodes' : Array<string>,
  'isOrderFreezeActive' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'createdAt' : bigint,
  'deliveryDate' : bigint,
  'addressLine' : string,
  'items' : Array<OrderItem>,
  'pincode' : string,
}
export interface OrderItem {
  'qty' : bigint,
  'productId' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'awaitingPayment' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'paymentLink' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : ProductCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductCategory = { 'car' : null } |
  { 'home' : null } |
  { 'shop' : null };
export interface ProductInput {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : ProductCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Subscription {
  'id' : bigint,
  'qty' : bigint,
  'isCancelled' : boolean,
  'userId' : Principal,
  'isPaused' : boolean,
  'createdAt' : bigint,
  'productId' : bigint,
  'addressLine' : string,
  'orderIds' : Array<bigint>,
  'phone' : string,
  'pincode' : string,
}
export interface User {
  'principal' : Principal,
  'isBlocked' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'phone' : string,
}
export interface UserProfile {
  'isBlocked' : boolean,
  'name' : string,
  'role' : UserRole,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'superAdmin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'cancelOrder' : ActorMethod<[bigint], Order>,
  'cancelSubscription' : ActorMethod<[bigint], Subscription>,
  /**
   * / Register caller as SUPER_ADMIN and admin - only works when no admin exists
   * / If caller already has a user entry, upgrades it to superAdmin (preserving createdAt)
   */
  'claimFirstAdmin' : ActorMethod<[string, string], User>,
  'createSubscription' : ActorMethod<
    [bigint, bigint, string, string, string],
    Subscription
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<User>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getCMSContent' : ActorMethod<[], CMSContent>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeliverySettings' : ActorMethod<[], DeliverySettings>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyProfile' : ActorMethod<[], User>,
  'getMySubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getNextSaturday' : ActorMethod<[], bigint>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasNoAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markPaymentPaid' : ActorMethod<[bigint], Order>,
  'pauseSubscription' : ActorMethod<[bigint], Subscription>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, bigint, PaymentMethod, string, string],
    Order
  >,
  'registerOrLogin' : ActorMethod<[string, string], User>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateCMSContent' : ActorMethod<[CMSTagline, CMSTerms, CMSSEO], undefined>,
  'updateDeliverySettings' : ActorMethod<[DeliverySettings], undefined>,
  'updateMyProfile' : ActorMethod<[string, string], User>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], Order>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];