/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'car' : IDL.Null,
  'home' : IDL.Null,
  'shop' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'category' : ProductCategory,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'category' : ProductCategory,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'awaitingPayment' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'paymentLink' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'productId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deliveryDate' : IDL.Int,
  'addressLine' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Text,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'qty' : IDL.Nat,
  'isCancelled' : IDL.Bool,
  'userId' : IDL.Principal,
  'isPaused' : IDL.Bool,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'addressLine' : IDL.Text,
  'orderIds' : IDL.Vec(IDL.Nat),
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'superAdmin' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'phone' : IDL.Text,
});
export const CMSSEO = IDL.Record({
  'seoTitle' : IDL.Text,
  'seoMeta' : IDL.Text,
});
export const CMSTerms = IDL.Record({
  'refundPolicy' : IDL.Text,
  'privacyPolicy' : IDL.Text,
  'shippingPolicy' : IDL.Text,
  'termsAndConditions' : IDL.Text,
});
export const CMSTagline = IDL.Record({
  'tagline' : IDL.Text,
  'festivalOffer' : IDL.Text,
  'popupActive' : IDL.Bool,
  'popupText' : IDL.Text,
});
export const CMSContent = IDL.Record({
  'seo' : CMSSEO,
  'terms' : CMSTerms,
  'tagline' : CMSTagline,
});
export const UserProfile = IDL.Record({
  'isBlocked' : IDL.Bool,
  'name' : IDL.Text,
  'role' : UserRole,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'subscriptionRevenue' : IDL.Nat,
  'dailyRevenue' : IDL.Nat,
  'weeklyRevenue' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const DeliverySettings = IDL.Record({
  'minOrderValue' : IDL.Nat,
  'allowedPincodes' : IDL.Vec(IDL.Text),
  'isOrderFreezeActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [Order], []),
  'cancelSubscription' : IDL.Func([IDL.Nat], [Subscription], []),
  'claimFirstAdmin' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'createSubscription' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Subscription],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getCMSContent' : IDL.Func([], [CMSContent], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDeliverySettings' : IDL.Func([], [DeliverySettings], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [User], ['query']),
  'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getNextSaturday' : IDL.Func([], [IDL.Int], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasNoAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPaymentPaid' : IDL.Func([IDL.Nat], [Order], []),
  'pauseSubscription' : IDL.Func([IDL.Nat], [Subscription], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Int, PaymentMethod, IDL.Text, IDL.Text],
      [Order],
      [],
    ),
  'registerOrLogin' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateCMSContent' : IDL.Func([CMSTagline, CMSTerms, CMSSEO], [], []),
  'updateDeliverySettings' : IDL.Func([DeliverySettings], [], []),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'car' : IDL.Null,
    'home' : IDL.Null,
    'shop' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'category' : ProductCategory,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'category' : ProductCategory,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'awaitingPayment' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'paymentLink' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'productId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deliveryDate' : IDL.Int,
    'addressLine' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Text,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'qty' : IDL.Nat,
    'isCancelled' : IDL.Bool,
    'userId' : IDL.Principal,
    'isPaused' : IDL.Bool,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'addressLine' : IDL.Text,
    'orderIds' : IDL.Vec(IDL.Nat),
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'superAdmin' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  const CMSSEO = IDL.Record({ 'seoTitle' : IDL.Text, 'seoMeta' : IDL.Text });
  const CMSTerms = IDL.Record({
    'refundPolicy' : IDL.Text,
    'privacyPolicy' : IDL.Text,
    'shippingPolicy' : IDL.Text,
    'termsAndConditions' : IDL.Text,
  });
  const CMSTagline = IDL.Record({
    'tagline' : IDL.Text,
    'festivalOffer' : IDL.Text,
    'popupActive' : IDL.Bool,
    'popupText' : IDL.Text,
  });
  const CMSContent = IDL.Record({
    'seo' : CMSSEO,
    'terms' : CMSTerms,
    'tagline' : CMSTagline,
  });
  const UserProfile = IDL.Record({
    'isBlocked' : IDL.Bool,
    'name' : IDL.Text,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'subscriptionRevenue' : IDL.Nat,
    'dailyRevenue' : IDL.Nat,
    'weeklyRevenue' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const DeliverySettings = IDL.Record({
    'minOrderValue' : IDL.Nat,
    'allowedPincodes' : IDL.Vec(IDL.Text),
    'isOrderFreezeActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [Order], []),
    'cancelSubscription' : IDL.Func([IDL.Nat], [Subscription], []),
    'claimFirstAdmin' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'createSubscription' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Subscription],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getCMSContent' : IDL.Func([], [CMSContent], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDeliverySettings' : IDL.Func([], [DeliverySettings], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [User], ['query']),
    'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getNextSaturday' : IDL.Func([], [IDL.Int], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasNoAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPaymentPaid' : IDL.Func([IDL.Nat], [Order], []),
    'pauseSubscription' : IDL.Func([IDL.Nat], [Subscription], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Int, PaymentMethod, IDL.Text, IDL.Text],
        [Order],
        [],
      ),
    'registerOrLogin' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateCMSContent' : IDL.Func([CMSTagline, CMSTerms, CMSSEO], [], []),
    'updateDeliverySettings' : IDL.Func([DeliverySettings], [], []),
    'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };